### PR TITLE
Add any type to errors in try/catch for RegisterRoutes across templates

### LINKED ISSUE #1076: RegisterRoutes try/catch error is of type 'unknown'.
The `error` in the `try/catch` of the template for `koa` middleware is missing `any` type which causes TS (`v4.4.3`) to throw `error TS2571: Object is of type 'unknown'`.
https://github.com/lukeautry/tsoa/blob/9ea032adb7a0885305cb8d6793a9b660fee45592/packages/cli/src/routeGeneration/templates/koa.hbs#L85

Edit: Also spotted these which are likely to cause the same issue with `hapi` and `express`:
https://github.com/lukeautry/tsoa/blob/9ea032adb7a0885305cb8d6793a9b660fee45592/packages/cli/src/routeGeneration/templates/hapi.hbs#L104
https://github.com/lukeautry/tsoa/blob/9ea032adb7a0885305cb8d6793a9b660fee45592/packages/cli/src/routeGeneration/templates/express.hbs#L84

### PR DESCRIPTION
**Pull request by itsjxck**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/lukeautry/tsoa/tree/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/lukeautry/tsoa/pulls) for the same update/change?
- [ ] Have you written unit tests?
- [ ] Have you written unit tests that cover the negative cases (i.e.: if bad data is submitted, does the library respond properly)?
- [x] This PR is associated with an existing issue?

Closes #1076

### CODE REVIEW

**Comment by WoH** [comment]
Maybe someone wants to improve the types in the future, but LGTM for now, thanks.

**Comment by WoH** [comment]
[v3.11.1](https://github.com/lukeautry/tsoa/releases/tag/v3.11.1) should be working with TS 4.4

**Comment by kibiz0r** [comment]
@WoH @itsjxck This breaks compatibility with tsc <4.x.

> error TS1196: Catch clause variable cannot have a type annotation

We're on 3.7.3 right now.

**Comment by WoH** [comment]
Thanks for the heads up, bad judgement on my part, sorry for the inconvenience. Hotfix here would be to cast errors as any outside of the catch, I'll hopefully find time to release that this week.

**Comment by kibiz0r** [comment]
Sounds good. Thanks for the quick reply!

**Comment by WoH** [comment]
[v3.11.2](https://www.npmjs.com/package/tsoa/v/3.11.2) is available on npm
