### ISSUE TITLE
v6.1.0 breaking change on Authentication middleware

### ISSUE THREAD

**Issue by sl33kr** [lukeautry/tsoa#1575]
Upon upgrading from v6.0.1 to v6.1.0 our project started getting build errors on our generated routes.ts attempting to invoke our authentication middleware.

```
src/routes/routes.ts:1703:83 - error TS2554: Expected 2-3 arguments, but got 4.
expressAuthentication(request, name, secMethod[name], response)
```

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Build does not fail in minor version upgrade

## Current Behavior

Build fails due to authentication method signature change.

## Possible Solution

This possibly only affects projects with `strict: true` in the compiler options. It appears the breaking change occurred in https://github.com/lukeautry/tsoa/pull/1557.

## Context (Environment)

Version of the library: 6.1.0
Version of NodeJS: 18.19.1
Version of Typescript: 5.1.3

- Confirm you were using yarn not npm: [ ]

**Comment by samuelexferri** [comment]
Same error still in v6.2.1
```
src/routes/routes.ts:29:39 - error TS2352: Conversion of type '(expressRequest: Request, securityName: string, scopes: string[]) => Promise<void>' to type '(req: Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>, securityName: string, scopes?: string[] | undefined, res?: Response<...> | undefined) => Promise<...>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of parameters 'expressRequest' and 'req' are incompatible.
    Type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is missing the following properties from type 'Request': cache, credentials, destination, integrity, and 13 more.

29 const expressAuthenticationRecasted = expressAuthentication as (req: ExRequest, securityName: string, scopes?: string[], res?: ExResponse) => Promise<any>;
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/routes/routes.ts:29
```

I suggest to add an unknown conversion
```
const expressAuthenticationRecasted = expressAuthentication as unknown as (req: ExRequest, securityName: string, scopes?: string[], res?: ExResponse) => Promise<any>;
```
