### ISSUE TITLE
[MAJOR] Cannot compile with 3.6.0

### ISSUE THREAD

**Issue by Hobart2967** [lukeautry/tsoa#943]
## Sorting

- **I'm submitting a ...**

  - [x ] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [ x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
It builds.

## Current Behavior
Building with typescript 3.9.9.
```
node_modules/@tsoa/runtime/dist/interfaces/response.d.ts:3:51 - error TS1110: Type expected.

3 export declare type HttpStatusCodeStringLiteral = `${HttpStatusCodeLiteral}`;
                                                  ~~~
Found 1 error.
```
## Possible Solution

Change line 3 to: `export declare type HttpStatusCodeStringLiteral = HttpStatusCodeLiteral`;

## Steps to Reproduce

Install, configure, build

## Context (Environment)

Version of the library: 3.6.0
Version of NodeJS: 10.19.0

- Confirm you were using yarn not npm: [x]

## Breaking change?

as mentioned...

**Comment by Hobart2967** [comment]
workaround: Downgrade.

**Comment by WoH** [comment]
Bump TS to 4.1 to add support for TLTs

**Comment by WoH** [comment]
https://github.com/lukeautry/tsoa/releases/tag/v3.6.1

**Comment by Hobart2967** [comment]
Thanks!
