### ISSUE TITLE
Recent TsoaRoute.Security interface change is breaking route generation

### ISSUE THREAD

**Issue by jorshali** [lukeautry/tsoa#278]
When using the @Security annotation with TSOA 2.2.0, it seems that recent changes to the Security interface found in tsoa-route.d.ts is causing the generated routes to fail compilation.  Take the following example:
```
@Route('myRoute')
@Security('mySecurity')
export class MyController {
    @Get()
    public async find(@Request() request: any): Promise<string[]> {
        // logic to find some data
    }
}
```
The generated route includes the following call `authenticateMiddleware([{ "name": "mySecurity" }])` which invokes the generated method:  `function authenticateMiddleware(security: TsoaRoute.Security[] = [])`

In version 2.1.8, the TsoaRoute.Security interface matched the structure of the parameter being sent in:
```
interface Security {
  name: string;
  scopes?: string[];
}
```
In version 2.2.0 a compilation error is being thrown, as the interface has been changed to:
```
interface Security {
  [key: string]: string[];
}
```
An array of strings are now expected for any key which doesn't match the call above in the generated route.

Given the change to the interface, it's not clear if the route generation needs to be updated or if the interface was changed erroneously.  If any further information is needed, please let me know.  Thanks for the great project!

**Comment by benjamin-carl** [comment]
Hi! I can confirm this behavior after upgrading from 2.1.8 to 2.2.0 - made me switch back to 2.1.8.

**Comment by endor** [comment]
This should be fixed now in the latest master. Could you please check?

**Comment by jorshali** [comment]
I just verified the latest master and everything is now working as expected.  Thanks for your help!
