### ISSUE TITLE
Current master doesn't compile on TS 3.2.2

### ISSUE THREAD

**Issue by HoldYourWaffle** [lukeautry/tsoa#438]
fixes #438
fixes #434
While fixing up #361 I encountered the following compilation error:
```
src/routeGeneration/templateHelpers.ts:466:36 - error TS2322: Type 'ModelSchema' is not assignable to type 'boolean'.
```

This project also occurs on the `master` branch and is *probably* caused by https://github.com/lukeautry/tsoa/commit/8344f9f8c7f6cf90ff039e05f0a5f8bd8cafb6b9 (at least that's what `git blame` tells me).

The error occurs in this piece of code:
https://github.com/lukeautry/tsoa/blob/8344f9f8c7f6cf90ff039e05f0a5f8bd8cafb6b9/src/routeGeneration/templateHelpers.ts#L439-L442
`this.models[refName]` is a `ModelSchema` but a `boolean` was expected. I think this is supposed to be a 'truthy' comparison, which made me think that this is actually a bug with Typescript.

After investigating why I didn't get this error before and especially how it passed the pre-commit hook. I found out that it doesn't occur when using TS 3.5.1 (which was installed in my clone due to #434). This is supported by the yarn.lock which lists TS 3.5.1 as the "actually installed version":
https://github.com/lukeautry/tsoa/blob/ecdd050c6859112f080e55e88f141624a86e8c90/yarn.lock#L2224-L2225

There's a second error caused by the lack of ES7 definitions (`includes` is not found on `string[]`). I encountered this problem with #434, it's solved by adding `es7` to the `lib` section in `tsconfig.json`. This error still occurs even when using TS 3.5.1, and I have no idea how that passed the pre-commit hook.

As a side note, shouldn't the Typescript version in `package.json` be locked down to an exact version (or maybe allow only patch versions), for the reason cited in #311?

**Comment by WoH** [comment]
I also experienced the issue with `Array.includes()` and believe I mentioned it, can't say where at the top of my head. But can confirm.
As the author of the lines in question, yes, that is a truthy comparison to ensure every subschema references a type tracked in the referenceMap :)

**Comment by HoldYourWaffle** [comment]
The truthy comparison should be fine, that was probably just a bug in tsc.

The `includes` error is strange though. In the issue you linked @dgreene1 mentions that `Array.includes` should be in `es6` which I thought was the case too. Adding `es7` to the `tsconfig.json` did solve the issue for me though.
He also says that it works fine for him, and that CodeShip is passing. I'm pretty sure it worked for me too at first but I'm not sure if I was still on a fallen-behind master branch then. Either way I can't get it to disappear anymore now...

**Comment by WoH** [comment]
Ok, just for the sake pf documentation. It's another yarn's ts vs. package-lock by npm difference. Tried to yarn install -> build -> worked.
Wiped, npm installed -> got exactly your described errors (even the ModelSchema issue).
Upgraded ts -> still got the es6 lib issue.
Run `npm upgrade @types/node` and see if you're fine now aswell. That's what did it for me.

**Comment by HoldYourWaffle** [comment]
Updating `@types/node` fixed the error, I updated #434 accordingly. Might be good to do a full dependency update & lock-file resync commit...

> I don't mind any of the 2 options I believe it makes sense to chose one to avoid confusion.

You mean the choice between yarn/npm?

**Comment by WoH** [comment]
> You mean the choice between yarn/npm?
Yeah.

Not sure it's related, but I think you might wanna upgrade the linter aswell: https://github.com/lukeautry/tsoa/pull/437#discussion_r316879447

**Comment by HoldYourWaffle** [comment]
> Might be good to do a full dependency update & lock-file resync commit...

@dgreene1 I'd be willing to create a PR/extend #434 for this if you want me to.

**Comment by dgreene1** [comment]
@HoldYourWaffle yes please make a PR for this. And is there a way that we can force contributors to only use npm or yarn?

**Comment by HoldYourWaffle** [comment]
There isn't really a way to "prohibit" the use of one or the other (that I know of), but [yarn is able to interpret the `package-lock.json` format](https://yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/) while npm can't read `yarn.lock`.
It still converts and creates its own lock-file though, so my suggestion would be to auto-delete this file in some npm script. Adding an entry in `.gitignore` is not enough because the file is still there, meaning it could (and most likely will) still cause issues.

**Comment by HoldYourWaffle** [comment]
I updated #434.
